Networking:
  - Networking/**/*

Content:
  - Content/**/*
  
Dashboard:
  - Dashboard/**/*
  
ScreenSharing:
  - ScreenSharing/**/*
    
Whiteboard:
  - Whiteboard/**/*
  
Client:
  - Client/**/*
    
Server:
  - Server/**/*

Testing:
  - Testing/**/*

documentation:
  - any: ['*.pdf']